<?php

// new sql
// rely on image cache?

function nycc_carousel_theme($existing, $type, $theme, $path) {
  return array(
    'nycc_carousel' => array(
      'template' => 'nycc-carousel',
      'variables' => array('slides' => array()),
    ),
  );
}

function nycc_carousel_nycc_carousel($variables) {
  return theme('nycc_carousel');
}

function nycc_carousel_block_info() {
  $blocks['nycc_carousel'] = array(
    'info' => t('NYCC Carousel'),
  );
  return $blocks;
}

function nycc_carousel_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'nycc_carousel':
      $block['subject'] = t('NYCC Carousel');
      $block['content'] = theme('nycc_carousel');
      break;
  }
  return $block;
}

function nycc_carousel_process_nycc_carousel(&$variables) {
  $variables['slides'] = _nycc_carousel_get_slides();
}

function _nycc_carousel_get_slides() {
  $slides = array();
  
  $filesdir = '/' . variable_get('file_public_path', conf_path() . 'files');
  
  $sql =<<<EOS
    SELECT n.nid, n.title, d.field_date_value, f.uri, b.body_value AS body
    FROM {node} n, {field_data_body} b, {field_data_field_date} d, {field_data_field_image_cache} i, {file_managed} f, {field_data_field_carousel_order} co 
    WHERE co.entity_id = n.nid AND co.revision_id = n.vid AND n.nid = d.entity_id AND n.vid = d.revision_id AND n.nid = b.entity_id AND n.vid = b.revision_id AND n.nid = i.entity_id AND n.vid = i.revision_id AND f.fid = i.field_image_cache_fid AND ((n.promote=1) AND ((n.type='event') OR (n.type='page')) AND (n.status <> 0)) 
    ORDER BY field_carousel_order_value ASC, field_date_value ASC 
    LIMIT 4
EOS;
  
  $results = db_query($sql);
  foreach ($results as $r) {
    $filename = str_replace('public://', "", $r->uri);
    $body = strip_tags($r->body);
    if (strlen($body) >= 90)
      $body = substr($body,0,87) .'...';
    //$imgpath = $filesdir . $filename;
    $imgpath =  $filesdir . "/styles/fpcarousel/public/" . $filename;
    $thumbpath = $filesdir . "/styles/thumbnail/public/" . $filename;
    $nodepath = drupal_get_path_alias("node/" . $r->nid);
    $date = $r->field_date_value;
    $title = $r->title;
    
    $slides[] = array('body' => $body, 'imgpath' => $imgpath, 'thumbpath' => $thumbpath, 'nodepath' => $nodepath, 'title' => $title, 'date' => $date, );
  } // for

  return $slides;
}


