<?php

/**
 * @file
 * The Block Export interface allows the user to select a single or multiple
 * blocks to export/import.
 *
 * @ author Devendra Yadav <dev.firoza@gmail.com>
 */

/**
 * Implements hook_help().
 */
function block_export_import_help($path, $arg) {
  switch ($path) {
    case 'admin/help#block-export-import':
      $output = '<h3>' . t('Installation') . '</h3>';
      $output .= '<p>' . t('Quite simple, Download the module and put into your
      your_drupal_site_path/sites/all/modules or
      your_drupal_site_path/sites/all/modules/contrib and install from your
      admin panel.') . '</p>';
      $output .= '<h3>' . t('Configuration') . '</h3>';
      $output .= '<p>' . t('After successful installation you able to export
      your all system specific blocks from Admin >> Site building >>
      Export Blocks') . '</p>';
      $output .= '<h3>' . t('Export Blocks') . '</h3>';
      $output .= '<p>' . t('Now click on Export tab.') . '</p>';
      $output .= '<p>' . t('Copy all the data form Export Block(s) Code
      textarea.') . '</p>';
      $output .= '<h3>' . t('Import Blocks') . '</h3>';
      $output .= '<p>' . t('Access the link
      admin/structure/export-import-block/import') . '</p>';
      $output .= '<p>' . t('Paste your exported code in displayed
      box.') . '</p>';
      $output .= '<p>' . t('Click on Import Blocks.') . '</p>';
      $output .= '<h3>' . t('Dependencies') . '</h3>';
      $output .= '<p>' . t('1. Block') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_menu().
 */
function block_export_import_menu() {
  $items['admin/build/export'] = array(
    'title' => 'Export',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('block_export_import_blocks_export_form'),
    'access arguments' => array('administer blocks'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/block.export.admin.inc',
    'weight' => 50,
  );

  $items['admin/build/export-import-block'] = array(
    'title' => 'Blocks Export/Import',
    'description' => 'Page to export/import blocks',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('block_export_import_blocks_export_form'),
    'access arguments' => array('administer blocks'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/block.export.admin.inc',
  );

  $items['admin/build/export-import-block/export'] = array(
    'title' => 'Export',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
  );

  $items['admin/build/export-import-block/import'] = array(
    'title' => 'Import',
    'description' => 'Page to import blocks',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('block_export_import_blocks_import_form'),
    'access arguments' => array('administer blocks'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/block.import.admin.inc',
  );
  return $items;
}
