<?php

/**
 * @file
 * Auto Tune Database
 */

/**
 * Implementation of hook_menu().
 */
function dbtuner_menu() {
  $items['admin/settings/dbtuner'] = array(
    'title' => 'DB Tuner',
    'description' => 'Add indexes to your database',
    'page callback' => 'dbtuner_indexes_page',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'dbtuner.admin.inc',
  );
  $items['admin/settings/dbtuner/index'] = array(
    'title' => 'Indexes',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );
  $items['admin/settings/dbtuner/explain-views'] = array(
    'title' => 'Explain Views',
    'description' => 'Run explain on every view query',
    'page callback' => 'dbtuner_explain_views_page',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'dbtuner.explain.inc',
    'weight' => 1,
  );
  $items['admin/settings/dbtuner/engine'] = array(
    'title' => 'Engine',
    'description' => 'Change Database Engine',
    'page callback' => 'dbtuner_engine_page',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'dbtuner.admin.inc',
    'weight' => 2,
  );
  $items['admin/settings/dbtuner/collation'] = array(
    'title' => 'Collation',
    'description' => 'Change Databases Collation',
    'page callback' => 'dbtuner_collation_page',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'dbtuner.admin.inc',
    'weight' => 3,
  );
  $items['admin/settings/dbtuner/mysqltuner'] = array(
    'title' => 'MySQL Tuner',
    'description' => 'Run database tuning script',
    'page callback' => 'dbtuner_mysqltuner_page',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'dbtuner.mysqltuner.inc',
    'weight' => 4,
  );
  $items['admin/settings/dbtuner/explain-slow-log'] = array(
    'title' => 'Explain Slow Query Log',
    'description' => 'Run explain on every query in the Slow Query Log',
    'page callback' => 'dbtuner_explain_slow_query_log_page',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'dbtuner.explain.inc',
    'weight' => 5,
  );
  return $items;
}


/**
 * Implementation of hook_views_api.
 */
function dbtuner_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'dbtuner'),
  );
}
