<?php
/**
 * @file nycc_migrate.migrate.inc
 */

/**
 * This is code for a Drupal 6 to Drupal 7 migration based on migrate_d2d example. This won't actually
 * work without defining the referenced vocabularies, content types, and fields
 * on each side.
 */

/**
 * Implements hook_migrate_api().
 */
function nycc_migrate_migrate_api() {
  /**
   * Declare the api version and migration group.
   */
  $api = array(
    'api' => 2,
    /*
    'groups' => array(
      'example_group' => array(
        'title' => t('Drupal 6 to Drupal 7 example migrations.'),
      ),
    ),
    'migrations' => array(),
    */
  );
  return $api;
}



/**
 * Implementation of hook_flush_caches()
 */
function nycc_migrate_flush_caches() {

  // Define all migrations in this function

  $common_arguments = array(
    'source_version' => 6,
    'source_connection' => 'd6test'
  );

  /**
   * We should do Performance -> Clear All Caches or "drush cc all" to enable migration options in the Content menu
   * Please note, migrate module uses hook_migrate_api() to handle migrations but migrate_d2d works like below
   */
  nycc_migrate_users($common_arguments);
  nycc_migrate_user_pictures($common_arguments);
}
  

// User migration
function nycc_migrate_users($common_arguments) {

  $args = $common_arguments + array(
    'description' => t('Import users from Drupal 6'),
    'machine_name' => 'UserMigration',
  );
 
  // Call Drupal-to-Drupal Migration module (using native class)
  Migration::registerMigration($migration_class="DrupalUser6Migration", 
    $args['machine_name'], $args);

}



// User picture migration
// https://www.drupal.org/node/1819706
// http://drupal.stackexchange.com/questions/155113/migrating-user-profile-picture-from-d6-to-d7
function nycc_migrate_user_pictures($common_arguments) {

  $picture_arguments = $common_arguments + array(
    'machine_name' => 'UserPicturesMigration',
    'description' => t('Import Drupal 6 picture files'),
    'default_uid' => 1,
    'source_dir' => '/var/www/html/d6/sites/default/files/pictures',
    'destination_dir' => 'public://pictures',
  );
  
  Migration::registerMigration('DrupalPicture6Migration', 
    $picture_arguments['machine_name'], $picture_arguments);
    
  // do we need this?
  // see:https://www.drupal.org/node/1819706#comment-6835928
  /*
  $user_arguments = $common_arguments + array(
    'machine_name' => 'ExampleUser',
    'description' => t('Import Drupal 6 users'),
    'picture_migration' => 'ExamplePicture',
    'soft_dependencies' => array('ExamplePicture'),
  );
  Migration::registerMigration('DrupalUser6Migration', 
    $user_arguments['machine_name'], $user_arguments);  
  */
}





