<?php

// new line comment here for git demo

// add buttons to rides node content
// theme will place in proper region (node--rides.tpl.php)
// uses bootstrap classes, can we push that to theme?

//function nycc_rides2_node_view($node, $view_mode, $langcode) {
//  global $user;
//  if ($node->type == 'rides' && $view_mode == 'full') {
//    
//    // todo: depending on button, check for paid member, check ride status approved, ride not passed, space available, wait list, check user not already joined, check user meets other validations (e.g., waiver acknowleged, emergency info exists, etc), some buttons are only for leaders (not a role).  Need functions for all this to keep this code clean.
//    
//    $nid = $node->nid;
//    
//    $buttons = array();
//    
//    $buttons[] = l(t('Join'), "node/$nid/join", array('attributes' => array('class' => array('btn', 'btn-primary', 'nycc-btn', 'nycc-join-btn'))));
//    
//    $buttons[] = l(t('Revise Ride Details'), "node/$nid/edit", array('attributes' => array('class' => array('btn', 'btn-primary', 'nycc-btn', 'nycc-edit-btn'))));
//    
//    $buttons[] = l(t('Withdraw'), "#", array('attributes' => array('class' => array('btn', 'nycc-btn', 'btn-primary', 'nycc-xxx-btn'))));
//    
//    $buttons[] = l(t('Re-list This Ride'), "#", array('attributes' => array('class' => array('btn', 'btn-primary', 'nycc-btn', 'nycc-xxx-btn'))));
//    
//    $buttons[] = l(t('Roster & Waiver Form'), "#", array('attributes' => array('class' => array('btn', 'btn-primary', 'nycc-btn', 'nycc-xxx-btn'))));
//    
//    $buttons[] = l(t('Email Participants '), "#", array('attributes' => array('class' => array('btn', 'btn-primary', 'nycc-btn', 'nycc-xxx-btn'))));
//    
//    $buttons[] = l(t('Ride Attendance'), "#", array('attributes' => array('class' => array('btn', 'btn-primary', 'nycc-btn', 'nycc-xxx-btn'))));
//    
//    $buttons[] = l(t('Email Leaders'), "#", array('attributes' => array('class' => array('btn', 'btn-primary', 'nycc-btn', 'nycc-xxx-btn'))));
//
//
//    
//    $node->content['nycc_buttons'] = array(
//      '#markup' => theme_item_list(array(
//                    'title' => '',
//                    'items' => $buttons,
//                    'type' => 'ul',
//                    'attributes' => array(),
//                   )),
//      // '#weight' => 100,
//      // '#theme' => 'function_name_without_theme',
//    );
//  } // rides
//} // hook_node_view

// alternative method, use template vars
// can be overridden in theme (nycc7_preprocess_node)
// code would be similar to above
// why favor one method over another
function nycc_rides2_preprocess_node(&$variables) {
  $node = $variables ['node'];
  $variables ['nycc_test'] = 'sample data';
  
  // available in tpl as $nycc_test, can print to display
  
} //nycc_rides2_preprocess_node




// todo: plan better place for this and how things like this are handled
// called by http://markus.test.nycc.org/admin/structure/block/manage/block/21/configure
// function to replace block code
// make this simpler 
// iterate over and array of nids ?
// note that $node->type may not exist (e.g. on view pages)

function nycc_rides2_renew_button_pages() {

  if (drupal_is_front_page()) {
    return TRUE;
  }

  if(arg(0) == "node" && arg(1) == 2  && arg(2) != "edit"){
    return true;
  }

  if(arg(0) == "node" && arg(1) == "45511" && arg(2) != "edit"){
    return true;
  }

  if(arg(0) == "node" && arg(1) == "27725" && arg(2) != "edit"){
    return true;
  }

  if(arg(0) == "node" && arg(1) == "13902" && arg(2) != "edit"){
    return true;
  }

  if(arg(0) == "node" && arg(1) == "45415" && arg(2) != "edit"){
    return true;
  }

  if(arg(0) == "node" && arg(1) == "4" && arg(2) != "edit"){
    return true;
  }

  if(arg(0) == "node" && arg(1) == "45416" && arg(2) != "edit"){
    return true;
  }

  if(arg(0) == "node" && arg(1) == "45421" && arg(2) != "edit"){
    return true;
  }

  if(arg(0) == "node" && arg(1) == "6" && arg(2) != "edit"){
    return true;
  }

  if(arg(0) == "node" && arg(1) == "5" && arg(2) != "edit"){
    return true;
  }

  if(arg(0) == "node" && arg(1) =="add" && arg(2) == "rides"){
    return true;
  }

  if(arg(0) == "node" && arg(1) =="45457" && arg(2) != "edit"){
    return true;
  }

  if(arg(0) == "node" && arg(1) =="45475" && arg(2) != "edit"){
    return true;
  }

  if(arg(0) == "node" && arg(1) =="45512" && arg(2) != "edit"){
    return true;
  }

  if(arg(0) == "node" && arg(1) =="45517" && arg(2) != "edit"){
    return true;
  }

  if(arg(0) == "node" && arg(1) =="45519" && arg(2) != "edit"){
    return true;
  }

  if(arg(0) == "node" && arg(1) =="45520" && arg(2) != "edit"){
    return true;
  }

  if(arg(0) == "node" && arg(1) =="45521" && arg(2) != "edit"){
    return true;
  }

  if(arg(0) == "upcoming-events"){
    return true;
  }

  $node = node_load(arg(1));
  if (!$node)
      return false;
  $node_type = $node->type;
  
  if($node_type == "rides"){
    if(arg(0)  != "current-riders"){
      return true;
    }
  }

  if($node_type == "region"){
    if(arg(2) != "edit"){
      return true;
    }
  }
  if($node_type == "cue_sheet"){
    if(arg(2) != "edit"){
      return true;
    }
  }

  if($node_type == "product"){
    if(arg(2) != "edit"){
      if(arg(1) != 27756){
        return true;
      }
    }
  }

  if($node_type == "message_board"){
    if(arg(2) != "edit"){
      return true;
    }
  }

} // nycc_rides2_renew_button_pages
